name: hello-world
on:
  push:
    paths: "src/main.cpp"
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile Code
        run: g++ main.cpp
      - run: ./a.out
